{
 "title": "GCBA Eco Bicis System",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "GCBA Ecobici distribution",
   "type": "geomap",
   "gridPos": { "h": 19, "w": 16, "x": 0, "y": 0 },
   "targets": [
    { "expr": "ecobici_station", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "# of bici stations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(ecobici_station)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Stations with more availability",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "topk(10, ecobici_station)", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Capacity status",
   "type": "table",
   "gridPos": { "h": 18, "w": 8, "x": 16, "y": 13 },
   "targets": [
    { "expr": "ecobici_station", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Top Availability time distribution",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 19 },
   "targets": [
    { "expr": "topk(10, ecobici_station)", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Avg. Ecobici availability in time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 31 },
   "targets": [
    { "expr": "avg(ecobici_station)", "legendFormat": "Avg. Availability" }
   ]
  }
 ]
}